deploy.yaml code change

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -29,7 +29,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-
       - name: Checkout
         uses: actions/checkout@v4
 
@@ -48,7 +47,6 @@ jobs:
               Environment=${{ env.ENVIRONMENT }} \
             --capabilities CAPABILITY_NAMED_IAM
 
-
   # ==========================================================
   # DATA
   # ==========================================================
@@ -59,7 +57,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-
       - name: Checkout
         uses: actions/checkout@v4
 
@@ -80,7 +77,6 @@ jobs:
               DBPassword=${{ secrets.DB_PASSWORD }} \
             --capabilities CAPABILITY_NAMED_IAM
 
-
   # ==========================================================
   # AUTH
   # ==========================================================
@@ -91,7 +87,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-
       - name: Checkout
         uses: actions/checkout@v4
 
@@ -100,6 +95,20 @@ jobs:
         with:
           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
           aws-region: ${{ env.AWS_REGION }}
+
+      - name: Verify Auth Token Secret
+        run: |
+          if [ -z "${{ secrets.CLOUDMART_AUTH_TOKEN }}" ]; then
+            echo "ERROR: CLOUDMART_AUTH_TOKEN secret is missing"
+            exit 1
+          fi
+
+          echo "CLOUDMART_AUTH_TOKEN secret found"
+
+      - name: Validate Auth Template
+        run: |
+          aws cloudformation validate-template \
+            --template-body file://cloudformation/auth-stack.yaml
 
       - name: Deploy Auth Stack
         run: |
